# Generated by Django 6.0 on 2025-12-23 13:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(help_text='Nombre del icono de FontAwesome o similar', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('horario', models.CharField(blank=True, max_length=200)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='servicios.categoria')),
            ],
        ),
    ]
