# Generated by Django 6.0 on 2025-12-23 16:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(choices=[('fa-school', 'Escuela'), ('fa-hospital', 'Centro de Salud'), ('fa-pills', 'Farmacia'), ('fa-key', 'Cerrajería'), ('fa-store', 'Comercio'), ('fa-utensils', 'Gastronomía'), ('fa-dumbbell', 'Deporte/Gimnasio')], default='fa-map-marker-alt', help_text='Seleccione un icono de FontAwesome', max_length=50),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.categoria'),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='horario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
