# Generated by Django 6.0 on 2025-12-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_categoria_icono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(choices=[('fa-school', 'Escuela'), ('fa-hospital', 'Centro de Salud'), ('fa-pills', 'Farmacia'), ('fa-key', 'Cerrajería'), ('fa-store', 'Comercio'), ('fa-utensils', 'Gastronomía'), ('fa-dumbbell', 'Deporte/Gimnasio'), ('fa-landmark', 'Municipalidad'), ('fa-fire', 'Bomberos'), ('fa-shield-alt', 'Policía'), ('fa-trees', 'Parque/Espacio Verde'), ('fa-library', 'Biblioteca')], default='fa-map-marker-alt', help_text='Seleccione un icono de FontAwesome', max_length=50),
        ),
    ]
